title: Rama Vishwanathan
#logo: /assets/img/IMG_0014.jpg
description: Research Projects in Computer Vision and Natural Language Processing
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
